import { Food, FoodStation } from "./schema.type";

export const data: Food[] = [
  {
    docId: "1",
    name: "English Breakfast Baked Beans",
    description: "",
    foodStation: FoodStation.CUCINA,
    nutritionalInfo: {
      calories: { value: 180, unit: "kcal" },
      protein: { value: 8, unit: "g" },
      carbohydrates: { value: 29, unit: "g" },
      fat: { value: 4, unit: "g" },
      saturatedFat: { value: 0, unit: "g" },
      cholestrol: { value: 0, unit: "mg" },
      dietaryFiber: { value: 6, unit: "g" },
      sodium: { value: 380, unit: "mg" },
      potassium: { value: 560, unit: "mg" },
      calcium: { value: 70, unit: "mg" },
      iron: { value: 2.4, unit: "mg" },
      transFat: { value: 0, unit: "g" },
      vitaminD: { value: 0, unit: "IU" },
      vitaminC: { value: 6, unit: "mg" },
      vitaminA: { value: 5, unit: "IU" },
      ingredients:
        "Cannellini Beans, Tomato Puree, Onions, Maple Syrup, Tomato Paste, Canola Oil, Worcestershire Sauce, Garlic, Salt, Paprika, Black Pepper, Thyme",
    },
    servingSize: { value: 0.5, unit: "cup" },
    dietaryRestrictions: [],
  },
  {
    docId: "2",
    name: "Quinoa",
    description: "",
    foodStation: FoodStation.CUCINA,
    nutritionalInfo: {
      calories: { value: 130, unit: "kcal" },
      protein: { value: 4, unit: "g" },
      carbohydrates: { value: 22, unit: "g" },
      fat: { value: 2.5, unit: "g" },
      saturatedFat: { value: 0, unit: "g" },
      cholestrol: { value: 0, unit: "mg" },
      dietaryFiber: { value: 3, unit: "g" },
      sodium: { value: 340, unit: "mg" },
      potassium: { value: 170, unit: "mg" },
      calcium: { value: 20, unit: "mg" },
      iron: { value: 1.5, unit: "mg" },
      transFat: { value: 0, unit: "g" },
      vitaminD: { value: 0, unit: "IU" },
      vitaminC: { value: 0, unit: "mg" },
      vitaminA: { value: 0, unit: "IU" },
      ingredients: "Quinoa, Water, Chicken Broth Concentrate",
    },
    servingSize: { value: 0.5, unit: "cup" },
    dietaryRestrictions: [],
  },
  {
    docId: "3",
    name: "Meatless Vegetarian Sausage Patty",
    description: "",
    foodStation: FoodStation.CUCINA,
    nutritionalInfo: {
      calories: { value: 70, unit: "kcal" },
      protein: { value: 9, unit: "g" },
      carbohydrates: { value: 4, unit: "g" },
      fat: { value: 2.5, unit: "g" },
      saturatedFat: { value: 0, unit: "g" },
      cholestrol: { value: 0, unit: "mg" },
      dietaryFiber: { value: 1, unit: "g" },
      sodium: { value: 250, unit: "mg" },
      potassium: { value: 100, unit: "mg" },
      calcium: { value: 0, unit: "mg" },
      iron: { value: 1.6, unit: "mg" },
      transFat: { value: 0, unit: "g" },
      vitaminD: { value: 0, unit: "IU" },
      vitaminC: { value: 0, unit: "mg" },
      vitaminA: { value: 0, unit: "IU" },
      ingredients: "Meatless Sausage",
    },
    servingSize: { value: 1, unit: "each" },
    dietaryRestrictions: [],
  },
  {
    docId: "4",
    name: "Blistered Grape Tomatoes",
    description: "",
    foodStation: FoodStation.CUCINA,
    nutritionalInfo: {
      calories: { value: 30, unit: "kcal" },
      protein: { value: 0, unit: "g" },
      carbohydrates: { value: 1, unit: "g" },
      fat: { value: 2.5, unit: "g" },
      saturatedFat: { value: 0, unit: "g" },
      cholestrol: { value: 0, unit: "mg" },
      dietaryFiber: { value: 0, unit: "g" },
      sodium: { value: 110, unit: "mg" },
      potassium: { value: 70, unit: "mg" },
      calcium: { value: 0, unit: "mg" },
      iron: { value: 0.1, unit: "mg" },
      transFat: { value: 0, unit: "g" },
      vitaminD: { value: 0, unit: "IU" },
      vitaminC: { value: 4, unit: "mg" },
      vitaminA: { value: 0, unit: "IU" },
      ingredients: "Tomatoes, Canola Oil, Salt, Black Pepper, Parsley, Thyme",
    },
    servingSize: { value: 1, unit: "ounce" },
    dietaryRestrictions: [],
  },
  {
    docId: "5",
    name: "White Rice",
    description: "",
    foodStation: FoodStation.RICE_STATION,
    nutritionalInfo: {
      calories: { value: 120, unit: "kcal" },
      protein: { value: 2, unit: "g" },
      carbohydrates: { value: 23, unit: "g" },
      fat: { value: 1.5, unit: "g" },
      saturatedFat: { value: 0, unit: "g" },
      cholestrol: { value: 0, unit: "mg" },
      dietaryFiber: { value: 1, unit: "g" },
      sodium: { value: 30, unit: "mg" },
      potassium: { value: 50, unit: "mg" },
      calcium: { value: 20, unit: "mg" },
      iron: { value: 0.9, unit: "mg" },
      transFat: { value: 0, unit: "g" },
      vitaminD: { value: 0, unit: "IU" },
      vitaminC: { value: 0, unit: "mg" },
      vitaminA: { value: 0, unit: "IU" },
      ingredients: "Water, Long Grain White Rice, Canola Oil, Salt",
    },
    servingSize: { value: 0.5, unit: "cup" },
    dietaryRestrictions: [],
  },
];
